# Generated by Django 5.0 on 2023-12-28 11:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('short_name', models.CharField(max_length=10)),
                ('description', models.TextField(max_length=200)),
                ('teacher', models.CharField(max_length=30)),
                ('link', models.URLField(null=True)),
                ('location', models.CharField(max_length=30, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('kind', models.PositiveIntegerField(choices=[(0, 'Lecture'), (1, 'Practice'), (2, 'Lab'), (3, 'Seminar'), (4, 'Exam'), (5, 'Other')])),
                ('repeat_type', models.PositiveIntegerField(choices=[(0, 'Every year'), (1, 'Every month'), (2, 'Every week'), (3, 'Every day')])),
                ('repeat_interval', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('short_name', models.CharField(max_length=10)),
                ('lessons', models.ManyToManyField(to='schedule.lesson')),
            ],
        ),
    ]
